server {
    listen 80;
    server_name app.example.com;

    access_log /var/log/nginx/digitalOcean.access.log;
    error_log /var/log/nginx/digitalOcean.error.log;

    location /static/ {
        alias /srv/digitalOcean/static/;
        try_files $uri =404;
        expires 7d;
        add_header Cache-Control "public";
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/myproject/myproject.sock;
        proxy_read_timeout 120;
    }
}
